### ISSUE TITLE
Eliminar código que no se use

### ISSUE THREAD

**Issue by ncuesta** [cam-ila/to_do_list#3]
El código que no se usa no sirve, por ende hay que borrarlo. Por poner un ejemplo, el `TasksController` no es usado. Otro: Hay hojas de estilos en blanco que no tiene sentido que estén presentes.

**Comment by cam-ila** [comment]
Hola, ya realice las correcciones, después lo podes mirar para ver si esta bien? Gracias!!

**Comment by ncuesta** [comment]
Perfecto, este ticket está resuelto.
